### ISSUE TITLE
Python Error 

### ISSUE THREAD

**Issue by richardgohth** [mikel-brostrom/yolov8_tracking#698]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

(venv) root@stratton:/strongsort_yolov8/Yolov5_StrongSORT_OSNet# !607
python track.py --yolo-weights yolov8n.pt --source /syn2/con_benchmarkvideo/VID_20221220_104833.mp4.rotate.mp4 
Traceback (most recent call last):
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/track.py", line 32, in <module>
    from yolov8.ultralytics.nn.autobackend import AutoBackend
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/yolov8/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/__init__.py", line 10, in <module>
    from ultralytics.hub.auth import Auth
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, request_with_credentials
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/utils.py", line 10, in <module>
    from ultralytics.yolo.utils import DEFAULT_CONFIG_DICT, LOGGER, RANK, SETTINGS, TryExcept, colorstr, emojis
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.configs import hydra_patch  # noqa (patch hydra CLI)
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/configs/__init__.py", line 8, in <module>
    from ultralytics.yolo.configs.hydra_patch import check_config_mismatch
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/configs/hydra_patch.py", line 12, in <module>
    from ultralytics.yolo.utils import LOGGER, colorstr
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 455, in <module>
    SETTINGS = get_settings()
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 410, in get_settings
    correct = settings.keys() == defaults.keys() \
AttributeError: 'NoneType' object has no attribute 'keys'

### Minimal Reproducible Example

(venv) root@stratton:/strongsort_yolov8/Yolov5_StrongSORT_OSNet# !607
python track.py --yolo-weights yolov8n.pt --source /syn2/con_benchmarkvideo/VID_20221220_104833.mp4.rotate.mp4 
Traceback (most recent call last):
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/track.py", line 32, in <module>
    from yolov8.ultralytics.nn.autobackend import AutoBackend
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/yolov8/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/__init__.py", line 10, in <module>
    from ultralytics.hub.auth import Auth
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, request_with_credentials
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/utils.py", line 10, in <module>
    from ultralytics.yolo.utils import DEFAULT_CONFIG_DICT, LOGGER, RANK, SETTINGS, TryExcept, colorstr, emojis
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.configs import hydra_patch  # noqa (patch hydra CLI)
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/configs/__init__.py", line 8, in <module>
    from ultralytics.yolo.configs.hydra_patch import check_config_mismatch
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/configs/hydra_patch.py", line 12, in <module>
    from ultralytics.yolo.utils import LOGGER, colorstr
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 455, in <module>
    SETTINGS = get_settings()
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 410, in get_settings
    correct = settings.keys() == defaults.keys() \
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by mikel-brostrom** [comment]
`from yolov8.ultralytics.nn.autobackend import AutoBackend` is the first yolov8 import in `track.py` which makes me think that you don't have the yolov8 folder at all.

**Comment by richardgohth** [comment]
(venv) root@stratton:/strongsort_yolov8/Yolov5_StrongSORT_OSNet# python track.py --yolo-weights yolov8n.pt
Traceback (most recent call last):
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/track.py", line 32, in <module>
    from yolov8.ultralytics.nn.autobackend import AutoBackend
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/yolov8/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.yolo.engine.model import YOLO
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.configs import hydra_patch  # noqa (patch hydra CLI)
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/configs/__init__.py", line 8, in <module>
    from ultralytics.yolo.configs.hydra_patch import check_config_mismatch
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/configs/hydra_patch.py", line 12, in <module>
    from ultralytics.yolo.utils import LOGGER, colorstr
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 455, in <module>
    SETTINGS = get_settings()
  File "/strongsort_yolov8/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 410, in get_settings
    correct = settings.keys() == defaults.keys() \
AttributeError: 'NoneType' object has no attribute 'keys'
(venv) root@stratton:/strongsort_yolov8/Yolov5_StrongSORT_OSNet# find . -name yolo
./yolov8/ultralytics/yolo
./venv/bin/yolo
./venv/lib/python3.9/site-packages/ultralytics/yolo

**Comment by mikel-brostrom** [comment]
An easy fix would be to re-clone the repo

**Comment by richardgohth** [comment]
Thanks.
Did find find the required yolo folder?
Yes have recloned many times, including from ultralytics github directly.
Always the same.
Tried with Ubuntu 18 and 20.
It works on my Jetson Xavier running ubuntu 20 albeit very slowly

**Comment by sabdha** [comment]
I am facing an error where I have to include yolov8 with all the imports from ultralytics in the scripts inside yolov8 folder.  For example "from ultralytics.hub", I had to change to "from yolov8.ultralytics.hub." otherwise I am facing an import module error. Can this be resolved somehow. I have to go inside each end every scripts inside ultralytics folder to include yolov8 at the import statements starting with " from ultralytics" to from yolov8.ultralytics. @mikel-brostrom . Thanks in advance. I clined multiple times. Still facing this issue.

**Comment by mmarada** [comment]
Facing the same issue. The track.py was working fine yesterday.

**Comment by richardgohth** [comment]
> An easy fix would be to re-clone the repo

i was able to run the yolov5 version.
Seems the error is with yolov8 setup.

**Comment by mikel-brostrom** [comment]
Everything is working fine in the CI pipeline... https://github.com/mikel-brostrom/yolov8_tracking/actions/runs/3937114121/jobs/6734266886

**Comment by mikel-brostrom** [comment]
The ultralytics package version under requirements is not fixed. So you probably have an updated one. Delete it and install the one i pushed to requirements

**Comment by richardgohth** [comment]
> The ultralytics package version under requirements is not fixed. So you probably have an updated one. Delete it and install the one I pushed to master
reclone and reinstalled,
same error
===
Installing collected packages: wcwidth, tensorboard-plugin-wit, pytz, pyasn1, pure-eval, ptyprocess, pickleshare, lap, executing, easydict, charset-normalizer, backcall, antlr4-python3-runtime, zipp, urllib3, typing-extensions, traitlets, tqdm, tensorboard-data-server, soupsieve, smmap, six, rsa, PyYAML, PySocks, pyparsing, pygments, pyasn1-modules, psutil, protobuf, prompt-toolkit, Pillow, pexpect, parso, packaging, oauthlib, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cublas-cu11, numpy, MarkupSafe, kiwisolver, idna, grpcio, fonttools, filelock, decorator, cycler, certifi, cachetools, absl-py, werkzeug, scipy, requests, python-dateutil, opencv-python, omegaconf, nvidia-cudnn-cu11, matplotlib-inline, jedi, importlib-metadata, google-auth, gitdb, contourpy, beautifulsoup4, asttokens, torch, stack-data, requests-oauthlib, pandas, matplotlib, markdown, hydra-core, gitpython, torchvision, thop, seaborn, ipython, google-auth-oauthlib, gdown, filterpy, tensorboard, ultralytics
Successfully installed MarkupSafe-2.1.2 Pillow-9.4.0 PySocks-1.7.1 PyYAML-6.0 absl-py-1.4.0 antlr4-python3-runtime-4.9.3 asttokens-2.2.1 backcall-0.2.0 beautifulsoup4-4.11.1 cachetools-5.2.1 certifi-2022.12.7 charset-normalizer-3.0.1 contourpy-1.0.7 cycler-0.11.0 decorator-5.1.1 easydict-1.10 executing-1.2.0 filelock-3.9.0 filterpy-1.4.5 fonttools-4.38.0 gdown-4.6.0 gitdb-4.0.10 gitpython-3.1.30 google-auth-2.16.0 google-auth-oauthlib-0.4.6 grpcio-1.51.1 hydra-core-1.3.1 idna-3.4 importlib-metadata-6.0.0 ipython-8.8.0 jedi-0.18.2 kiwisolver-1.4.4 lap-0.4.0 markdown-3.4.1 matplotlib-3.6.3 matplotlib-inline-0.1.6 numpy-1.24.1 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 oauthlib-3.2.2 omegaconf-2.3.0 opencv-python-4.7.0.68 packaging-23.0 pandas-1.5.3 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 prompt-toolkit-3.0.36 protobuf-3.20.3 psutil-5.9.4 ptyprocess-0.7.0 pure-eval-0.2.2 pyasn1-0.4.8 pyasn1-modules-0.2.8 pygments-2.14.0 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.7.1 requests-2.28.2 requests-oauthlib-1.3.1 rsa-4.9 scipy-1.10.0 seaborn-0.12.2 six-1.16.0 smmap-5.0.0 soupsieve-2.3.2.post1 stack-data-0.6.2 tensorboard-2.11.2 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 thop-0.1.1.post2209072238 torch-1.13.1 torchvision-0.14.1 tqdm-4.64.1 traitlets-5.8.1 typing-extensions-4.4.0 ultralytics-8.0.5 urllib3-1.26.14 wcwidth-0.2.6 werkzeug-2.2.2 zipp-3.11.0
(venv) root@stratton:/mikel/Yolov5_StrongSORT_OSNet# yolo
Traceback (most recent call last):
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/bin/yolo", line 5, in <module>
    from ultralytics.yolo.cli import cli
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/__init__.py", line 10, in <module>
    from ultralytics.hub.auth import Auth
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, request_with_credentials
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/utils.py", line 10, in <module>
    from ultralytics.yolo.utils import DEFAULT_CONFIG_DICT, LOGGER, RANK, SETTINGS, TryExcept, colorstr, emojis
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/__init__.py", line 5, in <module>
    from ultralytics.yolo.v8 import classify, detect, segment
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/predict.py", line 6, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 34, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 15, in <module>
    from ultralytics.yolo.utils import LOGGER, ROOT, yaml_load
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 400, in <module>
    SETTINGS = get_settings()
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 378, in get_settings
    correct = settings.keys() == defaults.keys() and \
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by mikel-brostrom** [comment]
So you are running this:

`(venv) root@stratton:/mikel/Yolov5_StrongSORT_OSNet# yolo`

@richardgohth?

**Comment by richardgohth** [comment]
yes.
minimum to reproduce the error

**Comment by mikel-brostrom** [comment]
I have no idea what you are trying to run. In any case it is nothing that we support in our repo.
If you experience issues running scripts in this repo please report back.

**Comment by richardgohth** [comment]
sorry my mistake in running the wrong command.
here it is , in accordance to your readme
===========
 python track.py --yolo-weights yolov8n.pt --source /syn2/con_benchmarkvideo/VID_20221220_104833.mp4.rotate.mp4 
Traceback (most recent call last):
  File "/mikel/Yolov5_StrongSORT_OSNet/track.py", line 32, in <module>
    from yolov8.ultralytics.nn.autobackend import AutoBackend
  File "/mikel/Yolov5_StrongSORT_OSNet/yolov8/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/__init__.py", line 10, in <module>
    from ultralytics.hub.auth import Auth
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, request_with_credentials
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/utils.py", line 10, in <module>
    from ultralytics.yolo.utils import DEFAULT_CONFIG_DICT, LOGGER, RANK, SETTINGS, TryExcept, colorstr, emojis
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/__init__.py", line 5, in <module>
    from ultralytics.yolo.v8 import classify, detect, segment
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/predict.py", line 6, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 34, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 15, in <module>
    from ultralytics.yolo.utils import LOGGER, ROOT, yaml_load
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 400, in <module>
    SETTINGS = get_settings()
  File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 378, in get_settings
    correct = settings.keys() == defaults.keys() and \
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by mikel-brostrom** [comment]
I recommend you to start from a clean slate, re-clone and run again. You still have the old repo name `Yolov5_StrongSORT_OSNet` which makes me think that you have not tried that. The updates could have messed up your environment

**Comment by richardgohth** [comment]
thanks again.
yes, sorry again, wrong repo as I copy and paste from readme file :(
here it is the correct repo.
============
(venv) root@stratton:/mikel/yolov8_tracking# python track.py --yolo-weights yolov8n.pt --source  /syn2/con_benchmarkvideo/VID_20221220_104833.mp4.rotate.mp4 
Traceback (most recent call last):
  File "/mikel/yolov8_tracking/track.py", line 32, in <module>
    from yolov8.ultralytics.nn.autobackend import AutoBackend
  File "/mikel/yolov8_tracking/yolov8/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import checks
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/hub/__init__.py", line 10, in <module>
    from ultralytics.hub.auth import Auth
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/hub/auth.py", line 5, in <module>
    from ultralytics.hub.utils import HUB_API_ROOT, request_with_credentials
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/hub/utils.py", line 10, in <module>
    from ultralytics.yolo.utils import DEFAULT_CONFIG_DICT, LOGGER, RANK, SETTINGS, TryExcept, colorstr, emojis
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/__init__.py", line 5, in <module>
    from ultralytics.yolo.v8 import classify, detect, segment
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/predict.py", line 6, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 34, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 15, in <module>
    from ultralytics.yolo.utils import LOGGER, ROOT, yaml_load
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 400, in <module>
    SETTINGS = get_settings()
  File "/mikel/yolov8_tracking/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/__init__.py", line 378, in get_settings
    correct = settings.keys() == defaults.keys() and \
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by mikel-brostrom** [comment]
Have you followed the instructions in README for how to clone the repo?

**Comment by richardgohth** [comment]
Thanks
From here
https://github.com/mikel-brostrom/yolov8_tracking/
I followed below ( but replaced wthe repository with https://github.com/mikel-brostrom/yolov8_tracking.git )
======
Installation
git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet.git  # clone recursively
cd Yolov5_StrongSORT_OSNet
pip install -r requirements.txt  # install dependencies

**Comment by mikel-brostrom** [comment]
Sorry cannot help you if you don't follow the instructions

**Comment by richardgohth** [comment]
This is what happens when I follow the readme file exactly
==
python track.py --yolo-weights yolov8n.pt --source /syn2/con_benchmarkvideo/VID_20221220_104833.mp4.rotate.mp4
Traceback (most recent call last):
File "/mikel/Yolov5_StrongSORT_OSNet/track.py", line 32, in
from yolov8.ultralytics.nn.autobackend import AutoBackend
File "/mikel/Yolov5_StrongSORT_OSNet/yolov8/ultralytics/init.py", line 5, in
from ultralytics.hub import checks
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/init.py", line 5, in
from ultralytics.hub import checks
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/init.py", line 10, in
from ultralytics.hub.auth import Auth
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/auth.py", line 5, in
from ultralytics.hub.utils import HUB_API_ROOT, request_with_credentials
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/hub/utils.py", line 10, in
from ultralytics.yolo.utils import DEFAULT_CONFIG_DICT, LOGGER, RANK, SETTINGS, TryExcept, colorstr, emojis
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/init.py", line 3, in
from . import v8
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/init.py", line 5, in
from ultralytics.yolo.v8 import classify, detect, segment
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/init.py", line 3, in
from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/v8/classify/predict.py", line 6, in
from ultralytics.yolo.engine.predictor import BasePredictor
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/engine/predictor.py", line 34, in
from ultralytics.nn.autobackend import AutoBackend
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/nn/autobackend.py", line 15, in
from ultralytics.yolo.utils import LOGGER, ROOT, yaml_load
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/init.py", line 400, in
SETTINGS = get_settings()
File "/mikel/Yolov5_StrongSORT_OSNet/venv/lib/python3.9/site-packages/ultralytics/yolo/utils/init.py", line 378, in get_settings
correct = settings.keys() == defaults.keys() and
AttributeError: 'NoneType' object has no attribute 'keys'
