### ISSUE TITLE
ImportError: cannot import name 'checks' from 'ultralytics.hub'

### ISSUE THREAD

**Issue by GianniGi** [mikel-brostrom/yolov8_tracking#700]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Other

### Bug

Hello, I've installed your framework with:
```
git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet.git  # clone recursively
cd Yolov5_StrongSORT_OSNet
pip install -r requirements.txt  # install dependencies

```
but I receive this error with any command

```
PS D:\sbin\Yolov5_StrongSORT_OSNet> python track.py --yolo-weights yolov8n.pt --source 'https://www.youtube.com/watch?v=G5dIB2oF6sQ'
Traceback (most recent call last):
  File "D:\sbin\Yolov5_StrongSORT_OSNet\track.py", line 32, in <module>
    from yolov8.ultralytics.nn.autobackend import AutoBackend
  File "D:\sbin\Yolov5_StrongSORT_OSNet\yolov8\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.hub import checks
**ImportError: cannot import name 'checks' from 'ultralytics.hub'** (C:\Users\username\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\hub\__init__.py)
```

### Environment

- yolo v8
- windows 10

**Comment by GianniGi** [comment]
Thanks, that worked, I uninstalled with
> pip uninstall ultralytics

and then manually installed the version in requirements.txt
> pip install ultralytics==version_required

This is now quite slow (but it's slow also when running the yolov8 alone, without your repository. I have a gpu, I'll try to learn where the problem is.

python track.py --yolo-weights yolov8s.pt --show-vid --source https://www.youtube.com/watch?v=EBhCrTPpdBI
