### ISSUE TITLE
numpy tensor requires grad

### ISSUE THREAD

**Issue by johanneskpp** [mikel-brostrom/yolov8_tracking#721]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I currently try to integrate your code in a head-detection project to track the movement of people in videos. When i call the .update()-function of my strongsort-tracker i get the following error:
```
Traceback (most recent call last):
   File "head_detection/launch.py", line 109, in <module>
     event_loop.run_until_complete(main())
   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
     return future.result()
   File "head_detection/launch.py", line 73, in main
     result = tracker.update(pred, im, im0, names)
   File "/opt/pysetup/head_detection/tracker.py", line 92, in update
     output = self._tracker.update(det.cpu(), im0)
   File "/opt/pysetup/yolov5DeepSort/trackers/strongsort/strong_sort.py", line 55, in update
     detections = [Detection(bbox_tlwh[i], conf, features[i]) for i, conf in enumerate(
   File "/opt/pysetup/yolov5DeepSort/trackers/strongsort/strong_sort.py", line 55, in <listcomp>
     detections = [Detection(bbox_tlwh[i], conf, features[i]) for i, conf in enumerate(
   File "/opt/pysetup/yolov5DeepSort/trackers/strongsort/sort/detection.py", line 32, in __init__
     self.feature = np.asarray(feature.cpu(), dtype=np.float32)
   File "/opt/pysetup/.venv/lib/python3.8/site-packages/torch/_tensor.py", line 958, in __array__
     return self.numpy().astype(dtype, copy=False)
 RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```
I am calling the update-method with the following parameters:
```

 det:  tensor([[7.95000e+02, 8.10000e+01, 8.63000e+02, 1.67000e+02, 8.30820e-01, 0.00000e+00],
         [1.03100e+03, 3.31000e+02, 1.16300e+03, 4.78000e+02, 8.14632e-01, 0.00000e+00],
         [7.33000e+02, 1.30000e+01, 7.59000e+02, 4.10000e+01, 5.74059e-01, 0.00000e+00],
         [4.81000e+02, 2.20000e+01, 5.15000e+02, 6.40000e+01, 5.66208e-01, 0.00000e+00]])
 det.shape:  torch.Size([4, 6])
 im0.shape:  (720, 1280, 3)
 im0.dtype:  uint8
```

While debugging and comparing with your project running with the track.py-file i could not figure out my problem. I think the error appears in the _get_features-method of the strong_sort.py. In your project this function returns features, that don't require grad. In my function the features require grad which leads to the error. I am currently using your project on version _46c25338898d072569290c4ee478a483ac2cd79e_. I hope you can help me.

**Comment by mikel-brostrom** [comment]
In:

`trackers/strongsort/sort/detection.py`

change

self.feature = np.asarray(feature.cpu(), dtype=np.float32)

to

self.feature = np.asarray(feature.detach().cpu().numpy(), dtype=np.float32)

**Comment by johanneskpp** [comment]
I know, that this would be a possible fix but i would prefer to avoid this because I do not have access to the code of your library directly. I am currently using it as git submodule in a docker container. Additionally i don't understand why my code does not behave like your demo project?

**Comment by henriksod** [comment]
Hi, which pytorch version are you using?
