### ISSUE TITLE
No module named 'models'.

### ISSUE THREAD

**Issue by as51340** [mikel-brostrom/yolov8_tracking#731]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Integrations, Other

### Bug

Hi I have a yolov5 model trained on a custom data which I want to use for tracking. However, after cloning your repo and doing:
```bash
git clone ...
conda create -n tracking
conda activate tracking
pip install -r requirements.txt
python3 track.py --imgsz 3264 --source ./t7.mp4 --yolo-weights ./best.pt --save-vid --save-txt
```
I get the following error:
```
usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
requirements: YOLOv8 requirement "models" not found, attempting AutoUpdate...
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-yloq9es4/models_fe242c8f74de4ada8735aa39281f1f77/setup.py", line 25, in <module>
          import models
        File "/tmp/pip-install-yloq9es4/models_fe242c8f74de4ada8735aa39281f1f77/models/__init__.py", line 23, in <module>
          from base import *
      ModuleNotFoundError: No module named 'base'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3 -> 23.0
[notice] To update, run: python3.9 -m pip install --upgrade pip
requirements: ❌ Command 'pip install "models"  ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/andi/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 332, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "/home/andi/.local/lib/python3.10/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/andi/.local/lib/python3.10/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/andi/.local/lib/python3.10/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andi/FER/year5/FootballPlayerTracking/tracker/track_with_team_classification.py", line 345, in <module>
    main(opt)
  File "/home/andi/FER/year5/FootballPlayerTracking/tracker/track_with_team_classification.py", line 340, in main
    run(**vars(opt))
  File "/home/andi/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/andi/FER/year5/FootballPlayerTracking/tracker/track_with_team_classification.py", line 103, in run
    model = AutoBackend(yolo_weights, device=device, dnn=dnn, fp16=half)
  File "/home/andi/FER/year5/FootballPlayerTracking/tracker/yolov8/ultralytics/nn/autobackend.py", line 74, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "/home/andi/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 348, in attempt_load_weights
    ckpt = torch_safe_load(w)  # load ckpt
  File "/home/andi/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 340, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "/home/andi/.local/lib/python3.10/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/andi/.local/lib/python3.10/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/andi/.local/lib/python3.10/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

### Environment

`pip list`:
```bash
Package                  Version
------------------------ --------------------
absl-py                  1.4.0
apturl                   0.5.2
asttokens                2.2.1
attrs                    22.1.0
backcall                 0.2.0
bcrypt                   3.2.0
beautifulsoup4           4.11.2
blinker                  1.4
Brlapi                   0.8.3
cachetools               5.3.0
certifi                  2020.6.20
chardet                  4.0.0
chrome-gnome-shell       0.0.0
click                    8.0.3
colorama                 0.4.4
comm                     0.1.2
command-not-found        0.3
contourpy                1.0.7
cryptography             3.4.8
cupshelpers              1.0
cycler                   0.11.0
dbus-python              1.2.18
debugpy                  1.6.4
decorator                5.1.1
defer                    1.0.6
distlib                  0.3.6
distro                   1.7.0
distro-info              1.1build1
duplicity                0.8.21
easydict                 1.10
elastic-transport        8.4.0
elasticsearch            8.4.3
entrypoints              0.4
executing                1.2.0
fasteners                0.14.1
filelock                 3.8.0
filterpy                 1.4.5
flake8                   6.0.0
Flask                    2.2.2
Flask-Cors               3.0.10
fonttools                4.38.0
future                   0.18.2
gdown                    4.6.2
gekko                    0.2.8
gensim                   4.0.0
gitdb                    4.0.10
GitPython                3.1.30
google-auth              2.16.0
google-auth-oauthlib     0.4.6
grpcio                   1.51.1
gyp                      0.1
httplib2                 0.20.2
idna                     3.3
igraph                   0.10.2
importlib-metadata       4.6.4
iniconfig                1.1.1
ipykernel                6.19.4
ipython                  8.8.0
ipywidgets               8.0.4
isort                    4.3.21
itsdangerous             2.1.2
jedi                     0.18.2
jeepney                  0.7.1
Jinja2                   3.1.2
joblib                   1.2.0
jupyter_client           7.4.8
jupyter_core             5.1.2
jupyterlab-widgets       3.0.5
keyring                  23.5.0
kiwisolver               1.4.4
language-selector        0.1
lap                      0.4.0
launchpadlib             1.10.16
lazr.restfulclient       0.14.4
lazr.uri                 1.0.6
lockfile                 0.12.2
louis                    3.20.0
macaroonbakery           1.3.1
Mako                     1.1.3
Markdown                 3.4.1
MarkupSafe               2.1.1
matplotlib               3.6.3
matplotlib-inline        0.1.6
mccabe                   0.7.0
mgp                      1.0.0
monotonic                1.6
more-itertools           8.10.0
mypy-extensions          0.4.3
nest-asyncio             1.5.6
netifaces                0.11.0
normflows                1.5
numpy                    1.23.1
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
oauthlib                 3.2.0
olefile                  0.46
opencv-python            4.7.0.68
packaging                21.3
pandas                   1.5.3
paramiko                 2.9.3
parso                    0.8.3
pastel                   0.2.1
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.0.1
pip                      22.3
platformdirs             2.5.2
pluggy                   1.0.0
poethepoet               0.18.1
prompt-toolkit           3.0.36
protobuf                 4.21.12
psutil                   5.9.0
ptyprocess               0.7.0
pure-eval                0.2.2
py                       1.11.0
py-cpuinfo               8.0.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycairo                  1.20.1
pycodestyle              2.10.0
pycups                   2.0.1
pyflakes                 3.0.1
pyg-lib                  0.1.0+pt113cpu
Pygments                 2.11.2
PyGObject                3.42.1
PyJWT                    2.3.0
pymacaroons              0.13.0
pymgclient               1.3.1
PyNaCl                   1.5.0
pyparsing                2.4.7
PyQt5                    5.15.7
PyQt5-Qt5                5.15.2
PyQt5-sip                12.11.0
pyRFC3339                1.1
PySocks                  1.7.1
python-apt               2.4.0
python-dateutil          2.8.2
python-debian            0.1.43ubuntu1
python-Levenshtein       0.12.1
python-xlib              0.29
pytz                     2022.1
pyudev                   0.22.0
pyxdg                    0.27
PyYAML                   5.4.1
pyzmq                    24.0.1
reportlab                3.6.8
requests                 2.25.1
requests-oauthlib        1.3.1
rsa                      4.9
scikit-learn             1.2.0
scipy                    1.10.0
seaborn                  0.12.2
SecretStorage            3.3.1
sentry-sdk               1.15.0
setuptools               65.5.0
six                      1.16.0
smart-open               6.2.0
smmap                    5.0.0
soupsieve                2.3.2.post1
stack-data               0.6.2
systemd-python           234
tensorboard              2.12.0
tensorboard-data-server  0.7.0
tensorboard-plugin-wit   1.8.1
texttable                1.6.4
thop                     0.1.1.post2209072238
threadpoolctl            3.1.0
toml                     0.10.2
tomli                    2.0.1
tomlkit                  0.11.5
torch                    1.13.1
torch-cluster            1.6.0+pt113cpu
torch-geometric          2.2.0
torch-scatter            2.1.0+pt113cpu
torch-sparse             0.6.16+pt113cpu
torch-spline-conv        1.2.1+pt113cpu
torchvision              0.14.1
tornado                  6.2
tqdm                     4.64.1
traitlets                5.8.0
typing_extensions        4.4.0
ubuntu-advantage-tools   8001
ubuntu-drivers-common    0.0.0
ufw                      0.36.1
ultralytics              8.0.20
unattended-upgrades      0.1
urllib3                  1.26.14
usb-creator              0.3.7
virtualenv               20.16.6
wadllib                  1.3.6
wcwidth                  0.2.5
Werkzeug                 2.2.2
wheel                    0.37.1
widgetsnbextension       4.0.5
wrapt                    1.14.1
xdg                      5
xkit                     0.0.0
zipp                     1.0.0
```

**Comment by mikel-brostrom** [comment]
Sorry, this has nothing to do with this repo. This is a pure Ultralytics error https://github.com/ultralytics/ultralytics. Ask there why you cannot load an old yolov5 model

**Comment by SuperbTUM** [comment]
@as51340 Hello. Have you addressed this issue with Yolov5 loading? Thanks.

**Comment by as51340** [comment]
> @as51340 Hello. Have you addressed this issue with Yolov5 loading? Thanks.

Unfortunately not but I think it is because YOLOv5 model is not yet supported for loading in Ultralytics.
