### ISSUE TITLE
about val.py problem

### ISSUE THREAD

**Issue by 969149731** [mikel-brostrom/yolov8_tracking#767]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

when i use val.py in windows 
it has error

val: yolo_weights=C:\adata\idepythonprojact_dl\yolov5-v7_tracking-8.0\yolov5-v7_tracking-8.0\weights\yolov5n.pt, reid_weights=C:\adata\idepythonprojact_dl\yolov5-v7_tracking-8.0\yolov5-v7_tracking-8.0\weights\osnet_x0_25_msmt17.pt, tracking_method=strongsort, name=exp, project=runs\track, exist_ok=False, benchmark=MOT17, split=train, eval_existing=, conf_thres=0.45, imgsz=[1280], device=[0]
Parse error at "'+https:/'": Expected string_end
Eval repo already downloaded
Traceback (most recent call last):
  File "C:\adata\idepythonprojact_dl\yolov5-v7_tracking-8.0\yolov5-v7_tracking-8.0\val.py", line 192, in <module>
    main(opt)
  File "C:\adata\idepythonprojact_dl\yolov5-v7_tracking-8.0\yolov5-v7_tracking-8.0\val.py", line 106, in main
    download_mot_dataset(dst_val_tools_folder, opt.benchmark)
  File "C:\adata\idepythonprojact_dl\yolov5-v7_tracking-8.0\yolov5-v7_tracking-8.0\val.py", line 46, in download_mot_dataset
    subprocess.run(["wget", "-nc", gt_data_url, "-O", dst_val_tools_folder / 'data.zip']) # python module has no -nc nor -N flag
  File "C:\asoft\Anaconda3\envs\pytorch\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\asoft\Anaconda3\envs\pytorch\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\asoft\Anaconda3\envs\pytorch\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

Process finished with exit code 1

please tell me how can sove this problem， thank you！！！

**Comment by 969149731** [comment]
谢谢 我还想请问一下自己在yolov5上训练的一个检测动物的数据集，我该怎么去验证整个模型的指标，运行val.py之后下载的数据集（MOT17）验证可以用在自己的动物检测数据集中当做衡量模型好坏指标吗，或者简单点说，我改怎么去验证自己数据集模型 指标，万分感谢能够抽出时间回答，谢谢！！！！
