### ISSUE TITLE
 Can't get attribute 'Model' on <module 'models.yolo'..........\models\yolo\__init__.py>

### ISSUE THREAD

**Issue by Shehjad-Ishan** [mikel-brostrom/yolov8_tracking#787]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

**I am trying to use my custom weights trained with Yolov5. It is in .pt format and getting this error:**

Traceback (most recent call last):
  File "C:\Users\USER\object_counting\Yolov5_DeepSort_Pytorch\track.py", line 365, in <module>
    main(opt)
  File "C:\Users\USER\object_counting\Yolov5_DeepSort_Pytorch\track.py", line 360, in main
    run(**vars(opt))
  File "C:\Users\USER\object_counting\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\USER\object_counting\Yolov5_DeepSort_Pytorch\track.py", line 104, in run
    model = AutoBackend(yolo_weights, device=device, dnn=dnn, fp16=half)
  File "C:\Users\USER\object_counting\Yolov5_DeepSort_Pytorch\yolov8\ultralytics\nn\autobackend.py", line 74, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "C:\Users\USER\object_counting\venv\lib\site-packages\ultralytics\nn\tasks.py", line 348, in attempt_load_weights
    ckpt = torch_safe_load(w)  # load ckpt
  File "C:\Users\USER\object_counting\venv\lib\site-packages\ultralytics\nn\tasks.py", line 332, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "C:\Users\USER\object_counting\venv\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\USER\object_counting\venv\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\Users\USER\object_counting\venv\lib\site-packages\torch\serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'Model' on <module 'models.yolo' from 'C:\\Users\\USER\\object_counting\\venv\\lib\\site-packages\\models\\yolo\\__init__.py'>
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to qui

**Comment by SuperbTUM** [comment]
@Shehjad-Ishan Did you solve this problem? I also encountered such an error.
