### ISSUE TITLE
requirements: YOLOv8 requirement "models" not found, attempting AutoUpdate...

### ISSUE THREAD

**Issue by benaitis** [mikel-brostrom/yolov8_tracking#803]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

**Here's the bug:**

```
requirements: YOLOv8 requirement "models" not found, attempting AutoUpdate...
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
requirements: ❌ Command 'pip install "models"  ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/nn/tasks.py", line 332, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/yolov8_tracking/track.py", line 365, in <module>
    main(opt)
  File "/content/yolov8_tracking/track.py", line 360, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/yolov8_tracking/track.py", line 104, in run
    model = AutoBackend(yolo_weights, device=device, dnn=dnn, fp16=half)
  File "/content/yolov8_tracking/yolov8/ultralytics/nn/autobackend.py", line 74, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/nn/tasks.py", line 348, in attempt_load_weights
    ckpt = torch_safe_load(w)  # load ckpt
  File "/usr/local/lib/python3.9/dist-packages/ultralytics/nn/tasks.py", line 340, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models'
```

My model is sitting in yolov8_tracking repository but still can't find it.
![image](https://user-images.githubusercontent.com/29859835/228912915-6b451818-ea1f-4122-8941-0c551b426843.png)

**Script I'm using for running:**
`!python track.py --yolo-weights yolov5s.pt --classes 0 36 --reid-weights osnet_x0_25_msmt17.pt --source match.mp4 --save-vid --save-txt --tracking-method deepocsort`

### Environment

Google Collab

**Comment by mikel-brostrom** [comment]
You cannot load old v5 models using ultralytics. You would need to retrain them with the new repo (v8)
