### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by yuriploc** [mikel-brostrom/yolov8_tracking#812]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

When running

```sh
python track.py --source 'rtsp://localhost:8554/road' --yolo-weights yolov8n.pt yolov8n-seg.pt --classes 2 3 5 7
```

I get

```sh
Successfully loaded pretrained weights from "/home/codes/yolov8_tracking/weights/osnet_x0_25_msmt17.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
[tensor([], device='cuda:0', size=(0, 38))]
Traceback (most recent call last):
  File "/home/codes/yolov8_tracking/track.py", line 366, in <module>
    main(opt)
  File "/home/codes/yolov8_tracking/track.py", line 361, in main
    run(**vars(opt))
  File "/home/.asdf/installs/python/3.10.5/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/codes/yolov8_tracking/track.py", line 167, in run
    proto = preds[1][-1]
TypeError: 'NoneType' object is not subscriptable
```

### Environment

- OS: Fedora
- Python: 3.10.5 (asdf)

### Minimal Reproducible Example

Just ran 

```sh
$ git clone --recurse-submodules https://github.com/mikel-brostrom/yolov8_tracking.git
$ pip install -r requirements.txt
$ python track.py --source 'rtsp://localhost:8554/road' --yolo-weights yolov8n.pt yolov8n-seg.pt --classes 2 3 5 7
```

**Comment by mikel-brostrom** [comment]
Why are you trying to load a detection and a segmentation model at the same time?

**Comment by yuriploc** [comment]
I was just experimenting with it. Without the seg model it works. But one of the README screenshots was running detection and segmentation at the same time. 🤷🏽

**Comment by mikel-brostrom** [comment]
The segmentation models outputs  bboxes as well :smile:

**Comment by yuriploc** [comment]
Thank you for the update.
