### ISSUE TITLE
评估遇到一些问题

### ISSUE THREAD

**Issue by youzixpz** [mikel-brostrom/yolov8_tracking#820]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking, Evaluation, Evolution

### Bug

使用deepocsort  和strongsort评估时mot17-mini数据集时都报错，不知道需要下载什么东西，应该是track无法正常进行
![1](https://user-images.githubusercontent.com/41287125/231155569-3c9315af-e02c-472e-b1f0-1fded5219b7b.jpg)

### Minimal Reproducible Example

(yolov7-t) F:\yolo-track\yolov8_tracking-master>python evolve.py --tracking-method strongsort --benchmark MOT17-mini evolve: yolo_weights=F:\yolo-track\yolov8_tracking-master\weights\yolov8s.pt, reid_weights=F:\yolo-track\yolov8_tracking-master\weights\osnet_x1_0_dukemtm creid.pt, tracking_method=strongsort, tracking_config=trackers\strongsort\configs\strongsort.yaml, name=exp, project=runs\evolve, exist_ok=False, benchmar k=MOT17-mini, split=train, eval_existing=, conf_thres=0.45, imgsz=[1280], device=[''], n_trials=1, resume=False, processes_per_device=2, objectives=['HOTA', 'MOTA', 'IDF1'] [I 2023-04-11 19:35:37,593] A new study created in memory with name: no-name-21856b8f-3a2c-4203-8a51-865465c7cbf3 [FrozenTrial(number=0, state=TrialState.WAITING, values=None, datetime_start=None, datetime_complete=None, params={}, user_attrs={}, system_attrs={'fixed_ params': {'ecc': True, 'ema_alpha': 0.8962157769329083, 'max_age': 40, 'max_dist': 0.1594374041012136, 'max_iou_dist': 0.5431835667667874, 'max_unmatched_preds': 0, 'mc_lambda': 0.995, 'n_init': 3, 'nn_budget': 100}}, intermediate_values={}, distributions={}, trial_id=0, value=None)] Eval repo already downloaded track: yolo_weights=[WindowsPath('F:/yolo-track/yolov8_tracking-master/weights/yolov8s.pt')], reid_weights=F:\yolo-track\yolov8_tracking-master\weights\os net_x1_0_dukemtmcreid.pt, tracking_method=strongsort, tracking_config=trackers\strongsort\configs\strongsort.yaml, source=assets\MOT17-mini\train\MOT17-02 -FRCNN\MOT17-02-FRCNN, imgsz=[1280, 1280], conf_thres=0.5299659852287024, iou_thres=0.3, max_det=1000, device=, show_vid=False, save_txt=True, save_conf=F alse, save_crop=False, save_trajectories=False, save_vid=False, nosave=False, classes=[0], agnostic_nms=False, augment=False, visualize=False, update=Fals e, project=runs\evolve, name=exp62, exist_ok=True, line_thickness=2, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False, vid_stride=1, retina_masks=False track: yolo_weights=[WindowsPath('F:/yolo-track/yolov8_tracking-master/weights/yolov8s.pt')], reid_weights=F:\yolo-track\yolov8_tracking-master\weights\os net_x1_0_dukemtmcreid.pt, tracking_method=strongsort, tracking_config=trackers\strongsort\configs\strongsort.yaml, source=assets\MOT17-mini\train\MOT17-04 -FRCNN\MOT17-04-FRCNN, imgsz=[1280, 1280], conf_thres=0.5299659852287024, iou_thres=0.3, max_det=1000, device=, show_vid=False, save_txt=True, save_conf=F alse, save_crop=False, save_trajectories=False, save_vid=False, nosave=False, classes=[0], agnostic_nms=False, augment=False, visualize=False, update=Fals e, project=runs\evolve, name=exp62, exist_ok=True, line_thickness=2, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False, vid_stride=1, retina_masks=False Ultralytics YOLOv8.0.70  Python-3.8.16 torch-1.13.1+cpu CPU Ultralytics YOLOv8.0.70  Python-3.8.16 torch-1.13.1+cpu CPU YOLOv8s summary (fused): 168 layers, 11156544 parameters, 0 gradients, 28.6 GFLOPs YOLOv8s summary (fused): 168 layers, 11156544 parameters, 0 gradients, 28.6 GFLOPs Traceback (most recent call last): Traceback (most recent call last):   File "E:\conda\envs\yolov7-t\lib\site-packages\urllib3\connection.py", line 174, in _new_conn   File "E:\conda\envs\yolov7-t\lib\site-packages\urllib3\connection.py", line 174, in _new_conn     conn = connection.create_connection(     conn = connection.create_connection(   File "E:\conda\envs\yolov7-t\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection   File "E:\conda\envs\yolov7-t\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection     raise err     raise err   File "E:\conda\envs\yolov7-t\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection   File "E:\conda\envs\yolov7-t\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection     sock.connect(sa)     sock.connect(sa) TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by youzixpz** [comment]
I work out it
