### ISSUE TITLE
Unable to run yolov8 in a GPU

### ISSUE THREAD

**Issue by chenyd0763** [mikel-brostrom/yolov8_tracking#836]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

This is my CLI command: python track.py --yolo-weights yolov8x.pt --source 0 --reid-weights osnet_x0_25_market1501.pt --device 0

 and this is what I got :track: yolo_weights=[WindowsPath('yolov8x.pt')], reid_weights=osnet_x0_25_market1501.pt, tracking_method=deepocsort, tracking_config=trackers\deepocsort\configs\deepocsort.yaml, source=0, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=0, show_vid=False, save_txt=False, save_conf=False, save_crop=False, save_trajectories=False, save_vid=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\track, name=exp, exist_ok=False, line_thickness=2, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False, vid_stride=1, retina_masks=False
Ultralytics YOLOv8.0.88  Python-3.9.16 torch-2.0.0+cpu
Traceback (most recent call last):
  File "C:\Users\haose\Github\yolov8\track.py", line 365, in <module>
    main(opt)
  File "C:\Users\haose\Github\yolov8\track.py", line 360, in main
    run(**vars(opt))
  File "C:\Users\haose\anaconda3\envs\yolo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\haose\Github\yolov8\track.py", line 102, in run
    device = select_device(device)
  File "C:\Users\haose\anaconda3\envs\yolo\lib\site-packages\ultralytics\yolo\utils\torch_utils.py", line 69, in select_device
    raise ValueError(f"Invalid CUDA 'device={device}' requested."
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

**Comment by chenyd0763** [comment]
Issue solved by upgrading the torch version
