### ISSUE TITLE
Chinese users cannot download weight files from Google Cloud Disk, causing errors.

### ISSUE THREAD

**Issue by luke110** [mikel-brostrom/yolov8_tracking#850]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Other

### Bug

 When I execute track.py, always appear this：
  E:\ProgramData\Anaconda3\envs\yolov8_tracking\python.exe E:/ProgramData/Anaconda3_projects/yolov8_tracking/track.py --yolo-weights yolov8n.pt
track: yolo_weights=[WindowsPath('yolov8n.pt')], reid_weights=E:\ProgramData\Anaconda3_projects\yolov8_tracking\weights\osnet_x0_25_msmt17.pt, tracking_method=deepocsort, tracking_config=trackers\deepocsort\configs\deepocsort.yaml, source=0, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=, show_vid=False, save_txt=False, save_conf=False, save_crop=False, save_trajectories=False, save_vid=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\track, name=exp, exist_ok=False, line_thickness=2, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False, vid_stride=1, retina_masks=False
Ultralytics YOLOv8.0.54  Python-3.8.16 torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
1/1: 0... Success  (inf frames of shape 640x480 at 30.00 FPS)

Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000023AD8C5EA60>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023AD8C5EA60>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/ProgramData/Anaconda3_projects/yolov8_tracking/track.py", line 366, in <module>
    main(opt)
  File "E:/ProgramData/Anaconda3_projects/yolov8_tracking/track.py", line 361, in main
    run(**vars(opt))
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:/ProgramData/Anaconda3_projects/yolov8_tracking/track.py", line 137, in run
    tracker = create_tracker(tracking_method, tracking_config, reid_weights, device, half)
  File "E:\ProgramData\Anaconda3_projects\yolov8_tracking\trackers\multi_tracker_zoo.py", line 69, in create_tracker
    botsort = OCSort(
  File "E:\ProgramData\Anaconda3_projects\yolov8_tracking\trackers\deepocsort\ocsort.py", line 360, in __init__
    self.embedder = ReIDDetectMultiBackend(weights=model_weights, device=device, fp16=fp16)
  File "E:\ProgramData\Anaconda3_projects\yolov8_tracking\trackers\strongsort\reid_multibackend.py", line 60, in __init__
    gdown.download(model_url, str(w), quiet=False)
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\gdown\download.py", line 161, in download
    res = sess.get(url, stream=True, verify=verify)
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\ProgramData\Anaconda3\envs\yolov8_tracking\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023AD8C5EA60>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

进程已结束,退出代码1

I am running this program in China, how should I solve this problem?

### Environment

Ultralytics YOLOv8.0.54  Python-3.8.16 torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce GTX 1050 Ti, 4096MiB)

**Comment by lynxhawk** [comment]
I upload osnet_x0_25_msmt17.pt to baiduyun. But I still recommand you get a vpn for further research.
链接：https://pan.baidu.com/s/123uSV-sxIM6WZeDTcz4myg?pwd=fxrr 
提取码：fxrr

**Comment by mikel-brostrom** [comment]
So google drive is not available from China even when using VPU? @lynxhawk

**Comment by lynxhawk** [comment]
> So google drive is not available from China even when using VPN? @lynxhawk

usually useful, but VPN sometimes fails due to configuration or node problems.

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolov8_tracking/issues/824

**Comment by mikel-brostrom** [comment]
> usually useful, but VPN sometimes fails due to configuration or node problems. Besides, it's easy to use vpn on win/Mac but it is more difficult on Linux.

Hmm, so models have to be uploaded to Baidu or similar for Chine users to get access to them? Do you know if they can be accessed if they are moved into a release?  @lynxhawk

**Comment by lynxhawk** [comment]
In China, if you don’t use a VPN, there is a 0% probability of being downloaded in Google drive, a probability of more than 50% in github, and a 100% probability in Baidu cloud network disk. 
In China, the connection to the github server is sometimes not stable, but there is a possibility that it can be downloaded.🤣
@mikel-brostrom

**Comment by mikel-brostrom** [comment]
I added a new default ReiD model which is better than OSNet. I uploaded it to a release. Could you please try and see if there are less problems now? @lynxhawk

**Comment by lynxhawk** [comment]
Thank you very much. I try to download them without VPN, and they can be downloaded. (Although the download is slow XD

**Comment by mikel-brostrom** [comment]
Then it looks like we solved it! These will be the new default ReID models as they are superior to OSNet. So I guess these will be the only ones available for Chinese users. Thank for helping our here @lynxhawk!

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolov8_tracking/issues/347, https://github.com/mikel-brostrom/yolov8_tracking/issues/553, https://github.com/mikel-brostrom/yolov8_tracking/issues/824

**Comment by luke110** [comment]
> 我以为VPN会解决这个问题。可悲的是，我不可能调试并尝试解决这个问题，因为它对我来说是不可重现的。如果你找到了解决方案，请随时为此提交公关@luke110�

Later, I realized the download of weight files by closing the firewall, restarting the computer, and then opening the vpn, which solved this bug.
