### ISSUE TITLE
tite extend outside image

### ISSUE THREAD

**Issue by banshee1796** [mikel-brostrom/yolov8_tracking#872]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I  combine the code with my stereo distance calculate code, and this problem occurs, then i try to run source code and this problem also occurs. I'm not a computer science major and It's my first programming project ,idk how to solve this problem, could you please help me :(

Traceback (most recent call last):
  File "D:\Desktop\yolov5_tracking-5.0\track.py", line 309, in <module>
    detect(opt)
  File "D:\Desktop\yolov5_tracking-5.0\track.py", line 206, in detect
    outputs[i] = deepsort_list[i].update(xywhs.cpu(), confs.cpu(), clss.cpu(), im0)
  File "D:\Desktop\yolov5_tracking-5.0\deep_sort\deep_sort.py", line 59, in update
    features = self._get_features(bbox_xywh, ori_img)
  File "D:\Desktop\yolov5_tracking-5.0\deep_sort\deep_sort.py", line 149, in _get_features
    features = self.extractor(im_crops)
  File "D:\Desktop\yolov5_tracking-5.0\deep_sort\deep\reid\torchreid\utils\feature_extractor.py", line 118, in __call__
    image = self.to_pil(element)
  File "D:\Python\Python39\site-packages\torchvision\transforms\transforms.py", line 234, in __call__
    return F.to_pil_image(pic, self.mode)
  File "D:\Python\Python39\site-packages\torchvision\transforms\functional.py", line 337, in to_pil_image
    return Image.fromarray(npimg, mode=mode)
  File "D:\Python\Python39\site-packages\PIL\Image.py", line 3103, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "D:\Python\Python39\site-packages\PIL\Image.py", line 3027, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "D:\Python\Python39\site-packages\PIL\Image.py", line 2969, in frombytes
    im.frombytes(data, decoder_name, args)
  File "D:\Python\Python39\site-packages\PIL\Image.py", line 825, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image

**Comment by mikel-brostrom** [comment]
Sorry, never encountered this error. If you made custom modifications it will be very hard to help you out without the code

**Comment by banshee1796** [comment]
I didn't made any modifications, all code are downloaded from https://github.com/mikel-brostrom/yolov8_tracking/tree/v5.0, just use my own yolov5. Is stereo camera allowed to be source in track.py?

**Comment by WestbrookZero** [comment]
@banshee1796  I have the same problem. Have you solved it？

**Comment by banshee1796** [comment]
> @banshee1796  I have the same problem. Have you solved it？

sorry i can barely recall the changes i made that day, i think you can reform the input image. i guess the error occurs when the system tries to process the feature from the image captured by mono camera but what your input is from stereo camera. that means the size dosent march
