### ISSUE TITLE
ReID Pytorch exporting to ONNX and TensorRT has been done. But...

### ISSUE THREAD

**Issue by bekim777** [mikel-brostrom/yolov8_tracking#888]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

Hi, Mikel.

I have tried to export ReID models from Pytorch(.pt) to ONNX(.onnx) and TensorRT(.engine).
I have tried for two ReID Pytorch models: 
mobilenetv2_x1_4_dukemtmcreid.pt, 
osnet_x0_25_msmt17.pt

And I have tried commands for export like below:
python reid_export.py --include onnx engine --device 0 --batch-size 30 --dynamic --weights weights/osnet_x0_25_msmt17.pt

.engine & .onnx files created, and I thought it had been done succesfully.

But, when I tried to use these TensorRT(ONNX) models for tracking inference, I have seen following errors:

Loading weights/mobilenetv2_x1_4_dukemtmcreid.engine for TensorRT inference...
Traceback (most recent call last):
  File "/home/test/yolov8_tracking/track.py", line 273, in <module>
    main(opt)
  File "/home/test/yolov8_tracking/track.py", line 268, in main
    run(**vars(opt))
  File "/home/test/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/test/yolov8_tracking/track.py", line 141, in run
    run_callbacks('on_predict_start')
  File "/home/test/anaconda3/envs/strongsort_yolov8/lib/python3.10/site-packages/ultralytics/yolo/engine/predictor.py", line 339, in run_callbacks
    callback(self)
  File "/home/test/yolov8_tracking/track.py", line 34, in on_predict_start
    tracker = create_tracker(
  File "/home/test/yolov8_tracking/trackers/multi_tracker_zoo.py", line 10, in create_tracker
    strongsort = StrongSORT(
  File "/home/test/yolov8_tracking/trackers/strongsort/strong_sort.py", line 33, in __init__
    self.model = ReIDDetectMultiBackend(weights=model_weights, device=device, fp16=fp16)
  File "/home/test/yolov8_tracking/trackers/deep/reid_multibackend.py", line 98, in __init__
    if device.type == 'cpu':
AttributeError: 'NoneType' object has no attribute 'type'

I have tried commands for inference like below:
python track.py --yolo-model apron_eo_100epochs_1280_V2_YOLOv8.pt --tracking-method strongsort --source Singapore2.mp4 --device 0 --reid-model weights/mobilenetv2_x1_4_dukemtmcreid.engine

So, now I am not sure about the TensorRT(ONNX) is made correctly by using 'reid_export.py'...
Have you ever seen the cases like this? 
How can I sove the problem?

Best regards.

### Environment

OS: Ubuntu 20.04

**Comment by mikel-brostrom** [comment]
Thanks for reporting @bekim777. There may be some bugs after the last refactor. I am traveling today so won't be able to fix this until tomorrow.

**Comment by mikel-brostrom** [comment]
I encountered this same issue. This should be fixed now :rocket: 

```
(YDSO) ➜  yolov8_tracking git:(master) ✗ python track.py --source 0 --save --yolo-model yolov8s-seg.pt --tracking-method deepocsort --reid-model weights/osnet_x0_25_msmt17.onnx
track: yolo_model=yolov8s-seg.pt, reid_model=weights/osnet_x0_25_msmt17.onnx, tracking_method=deepocsort, source=0, imgsz=[640], conf=0.5, device=, show=False, save=True, classes=None, project=/home/mikel.brostrom/yolov8_tracking/runs/track, name=exp, exists_ok=False, half=False, vid_stride=1, hide_label=False, hide_conf=False
1/1: 0... Success ✅ (inf frames of shape 640x480 at 30.00 FPS)

Loading weights/osnet_x0_25_msmt17.onnx for ONNX Runtime inference...
2023-05-21 10:24:53.507980557 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:541 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
0: 480x640 1 person, YOLO 854.8ms, TRACKING 217.7ms
0: 480x640 1 person, YOLO 24.3ms, TRACKING 32.6ms
0: 480x640 1 person, YOLO 25.0ms, TRACKING 42.7ms
0: 480x640 1 person, YOLO 26.2ms, TRACKING 21.5ms
0: 480x640 1 person, YOLO 24.6ms, TRACKING 25.7ms
0: 480x640 1 person, YOLO 24.9ms, TRACKING 12.7ms
0: 480x640 1 person, YOLO 25.4ms, TRACKING 42.8ms
```

Thanks again for reporting!
